name: tiny_invariant
version: 1.0.0
description: A tiny implementation of the invariant function in Dart.
repository: https://github.com/zagmi/tiny_invariant
homepage: https://github.com/zagmi/tiny_invariant

environment:
  sdk: ">=2.14.0 <3.1.0"
  
dependencies:
  dotenv: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
